version: '3'

services:

  machine:
    image: appdynamcis/machine:${APPD_AGENT_MAJOR_VERSION}_bundle
    build:
      context: .
      dockerfile: ./machine/Dockerfile
      args:
        APPD_MACHINE_AGENT_VERSION:
        APPD_MACHINE_AGENT_SHA256:
  tomcat9-jre8:
    image: appdynamics/java:${APPD_AGENT_MAJOR_VERSION}_tomcat9-jre8
    build:
      context: .
      dockerfile: ./tomcat/9/jre8/Dockerfile
      args:
        APPD_AGENT_VERSION:
        APPD_AGENT_SHA256:
