version: '3'

services:
  machine:
    image: appdynamics/machine:${APPD_AGENT_MAJOR_VERSION}
    container_name: machineagent-nojre
    build:
      context: .
      dockerfile: ./machine/Dockerfile
      args:
        APPD_MACHINE_AGENT_VERSION:
        APPD_MACHINE_AGENT_SHA256:
        APPD_MACHINE_AGENT_MONITOR:
    image: appdynamics/tomcat9-jre8:${APPD_AGENT_MAJOR_VERSION}_sidecar
    container_name: sidecar_agentrepo
    build:
      context: .
      dockerfile: ./sidecar/Dockerfile
      args:
        APPD_AGENT_VERSION:
        APPD_AGENT_SHA256:
